name: Second
on:
 push:
  branches:
  - workflows2

jobs:
 job1:
  name: 'Trabajo 1'
  runs-on: ubuntu-22.04
  steps:
  - uses: actions/checkout@v3
  - run: python eati.py Workflow Dependencies
 job2:
  name: 'Trabajo 2'
  runs-on: windows-2019
  steps:
  - run: Get-Command
 job3:
  #Depende de job1 y job2
  needs: [job1, job2]
  name: 'Trabajo 3'
  runs-on: ubuntu-latest
  steps:
  - run: env
 job4:
  name: 'Trabajo 4'
  runs-on: ubuntu-latest
  steps:
  - run: cat /etc/*release
 job5:
  #Depende de job3 y job4
  needs: [job3, job4]
  name: 'Trabajo 5'
  runs-on: ubuntu-latest
  steps:
  - run: echo 'Fin workflow'