name: First
on:
 push:
  branches:
  - workflow3

jobs:
 job1:
  name: 'Checkout job'
  runs-on: Ubuntu-latest
  steps:
  - uses: actions/checkout@v3
    with: 
     repository: jmoyano/eati2023
     ref: main
     path: ./eati
  - run: cat eati/message.txt
  - uses: actions/checkout@v3
    with: 
     repository: jmoyano/eati2023
     ref: anotherbranch
     path: ./eati
  - run: cat eati/message.txt